// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: persist.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Agwinterm.Core.Persist {

  /// <summary>Holder for reflection information generated from persist.proto</summary>
  public static partial class PersistReflection {

    #region Descriptor
    /// <summary>File descriptor for persist.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PersistReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg1wZXJzaXN0LnByb3RvEhFhZ3dpbnRlcm0ucGVyc2lzdCKxAQoFUENlbGwS",
            "DAoEcnVuZRgBIAEoBRIKCgJmZxgCIAEoDRIKCgJiZxgDIAEoDRINCgVhdHRy",
            "cxgEIAEoDRINCgV3aWR0aBgFIAEoDRIPCgdmZ19raW5kGAYgASgNEhAKCGZn",
            "X2luZGV4GAcgASgNEg4KBmZnX3JnYhgIIAEoDRIPCgdiZ19raW5kGAkgASgN",
            "EhAKCGJnX2luZGV4GAogASgNEg4KBmJnX3JnYhgLIAEoDSIvCgRQUm93EicK",
            "BWNlbGxzGAEgAygLMhguYWd3aW50ZXJtLnBlcnNpc3QuUENlbGwiTwoHUEJ1",
            "ZmZlchIPCgd2ZXJzaW9uGAEgASgNEgwKBGNvbHMYAiABKA0SJQoEcm93cxgD",
            "IAMoCzIXLmFnd2ludGVybS5wZXJzaXN0LlBSb3dCGaoCFkFnd2ludGVybS5D",
            "b3JlLlBlcnNpc3RiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Agwinterm.Core.Persist.PCell), global::Agwinterm.Core.Persist.PCell.Parser, new[]{ "Rune", "Fg", "Bg", "Attrs", "Width", "FgKind", "FgIndex", "FgRgb", "BgKind", "BgIndex", "BgRgb" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Agwinterm.Core.Persist.PRow), global::Agwinterm.Core.Persist.PRow.Parser, new[]{ "Cells" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Agwinterm.Core.Persist.PBuffer), global::Agwinterm.Core.Persist.PBuffer.Parser, new[]{ "Version", "Cols", "Rows" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// One cell. Colours are 0x00RRGGBB; specs mirror ColorSpec (kind 0 default /
  /// 1 indexed / 2 rgb). Fields are packed to keep the blob small: most cells are
  /// a rune with default everything, so proto3's "omit defaults" does the work.
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class PCell : pb::IMessage<PCell>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PCell> _parser = new pb::MessageParser<PCell>(() => new PCell());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PCell> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Agwinterm.Core.Persist.PersistReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PCell() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PCell(PCell other) : this() {
      rune_ = other.rune_;
      fg_ = other.fg_;
      bg_ = other.bg_;
      attrs_ = other.attrs_;
      width_ = other.width_;
      fgKind_ = other.fgKind_;
      fgIndex_ = other.fgIndex_;
      fgRgb_ = other.fgRgb_;
      bgKind_ = other.bgKind_;
      bgIndex_ = other.bgIndex_;
      bgRgb_ = other.bgRgb_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PCell Clone() {
      return new PCell(this);
    }

    /// <summary>Field number for the "rune" field.</summary>
    public const int RuneFieldNumber = 1;
    private int rune_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Rune {
      get { return rune_; }
      set {
        rune_ = value;
      }
    }

    /// <summary>Field number for the "fg" field.</summary>
    public const int FgFieldNumber = 2;
    private uint fg_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Fg {
      get { return fg_; }
      set {
        fg_ = value;
      }
    }

    /// <summary>Field number for the "bg" field.</summary>
    public const int BgFieldNumber = 3;
    private uint bg_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Bg {
      get { return bg_; }
      set {
        bg_ = value;
      }
    }

    /// <summary>Field number for the "attrs" field.</summary>
    public const int AttrsFieldNumber = 4;
    private uint attrs_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Attrs {
      get { return attrs_; }
      set {
        attrs_ = value;
      }
    }

    /// <summary>Field number for the "width" field.</summary>
    public const int WidthFieldNumber = 5;
    private uint width_;
    /// <summary>
    /// 1 normal, 2 wide lead, 0 trailing spacer
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Width {
      get { return width_; }
      set {
        width_ = value;
      }
    }

    /// <summary>Field number for the "fg_kind" field.</summary>
    public const int FgKindFieldNumber = 6;
    private uint fgKind_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint FgKind {
      get { return fgKind_; }
      set {
        fgKind_ = value;
      }
    }

    /// <summary>Field number for the "fg_index" field.</summary>
    public const int FgIndexFieldNumber = 7;
    private uint fgIndex_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint FgIndex {
      get { return fgIndex_; }
      set {
        fgIndex_ = value;
      }
    }

    /// <summary>Field number for the "fg_rgb" field.</summary>
    public const int FgRgbFieldNumber = 8;
    private uint fgRgb_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint FgRgb {
      get { return fgRgb_; }
      set {
        fgRgb_ = value;
      }
    }

    /// <summary>Field number for the "bg_kind" field.</summary>
    public const int BgKindFieldNumber = 9;
    private uint bgKind_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint BgKind {
      get { return bgKind_; }
      set {
        bgKind_ = value;
      }
    }

    /// <summary>Field number for the "bg_index" field.</summary>
    public const int BgIndexFieldNumber = 10;
    private uint bgIndex_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint BgIndex {
      get { return bgIndex_; }
      set {
        bgIndex_ = value;
      }
    }

    /// <summary>Field number for the "bg_rgb" field.</summary>
    public const int BgRgbFieldNumber = 11;
    private uint bgRgb_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint BgRgb {
      get { return bgRgb_; }
      set {
        bgRgb_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PCell);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PCell other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Rune != other.Rune) return false;
      if (Fg != other.Fg) return false;
      if (Bg != other.Bg) return false;
      if (Attrs != other.Attrs) return false;
      if (Width != other.Width) return false;
      if (FgKind != other.FgKind) return false;
      if (FgIndex != other.FgIndex) return false;
      if (FgRgb != other.FgRgb) return false;
      if (BgKind != other.BgKind) return false;
      if (BgIndex != other.BgIndex) return false;
      if (BgRgb != other.BgRgb) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Rune != 0) hash ^= Rune.GetHashCode();
      if (Fg != 0) hash ^= Fg.GetHashCode();
      if (Bg != 0) hash ^= Bg.GetHashCode();
      if (Attrs != 0) hash ^= Attrs.GetHashCode();
      if (Width != 0) hash ^= Width.GetHashCode();
      if (FgKind != 0) hash ^= FgKind.GetHashCode();
      if (FgIndex != 0) hash ^= FgIndex.GetHashCode();
      if (FgRgb != 0) hash ^= FgRgb.GetHashCode();
      if (BgKind != 0) hash ^= BgKind.GetHashCode();
      if (BgIndex != 0) hash ^= BgIndex.GetHashCode();
      if (BgRgb != 0) hash ^= BgRgb.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Rune != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Rune);
      }
      if (Fg != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Fg);
      }
      if (Bg != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(Bg);
      }
      if (Attrs != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(Attrs);
      }
      if (Width != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(Width);
      }
      if (FgKind != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(FgKind);
      }
      if (FgIndex != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(FgIndex);
      }
      if (FgRgb != 0) {
        output.WriteRawTag(64);
        output.WriteUInt32(FgRgb);
      }
      if (BgKind != 0) {
        output.WriteRawTag(72);
        output.WriteUInt32(BgKind);
      }
      if (BgIndex != 0) {
        output.WriteRawTag(80);
        output.WriteUInt32(BgIndex);
      }
      if (BgRgb != 0) {
        output.WriteRawTag(88);
        output.WriteUInt32(BgRgb);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Rune != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(Rune);
      }
      if (Fg != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Fg);
      }
      if (Bg != 0) {
        output.WriteRawTag(24);
        output.WriteUInt32(Bg);
      }
      if (Attrs != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(Attrs);
      }
      if (Width != 0) {
        output.WriteRawTag(40);
        output.WriteUInt32(Width);
      }
      if (FgKind != 0) {
        output.WriteRawTag(48);
        output.WriteUInt32(FgKind);
      }
      if (FgIndex != 0) {
        output.WriteRawTag(56);
        output.WriteUInt32(FgIndex);
      }
      if (FgRgb != 0) {
        output.WriteRawTag(64);
        output.WriteUInt32(FgRgb);
      }
      if (BgKind != 0) {
        output.WriteRawTag(72);
        output.WriteUInt32(BgKind);
      }
      if (BgIndex != 0) {
        output.WriteRawTag(80);
        output.WriteUInt32(BgIndex);
      }
      if (BgRgb != 0) {
        output.WriteRawTag(88);
        output.WriteUInt32(BgRgb);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Rune != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Rune);
      }
      if (Fg != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Fg);
      }
      if (Bg != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Bg);
      }
      if (Attrs != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Attrs);
      }
      if (Width != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Width);
      }
      if (FgKind != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(FgKind);
      }
      if (FgIndex != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(FgIndex);
      }
      if (FgRgb != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(FgRgb);
      }
      if (BgKind != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(BgKind);
      }
      if (BgIndex != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(BgIndex);
      }
      if (BgRgb != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(BgRgb);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PCell other) {
      if (other == null) {
        return;
      }
      if (other.Rune != 0) {
        Rune = other.Rune;
      }
      if (other.Fg != 0) {
        Fg = other.Fg;
      }
      if (other.Bg != 0) {
        Bg = other.Bg;
      }
      if (other.Attrs != 0) {
        Attrs = other.Attrs;
      }
      if (other.Width != 0) {
        Width = other.Width;
      }
      if (other.FgKind != 0) {
        FgKind = other.FgKind;
      }
      if (other.FgIndex != 0) {
        FgIndex = other.FgIndex;
      }
      if (other.FgRgb != 0) {
        FgRgb = other.FgRgb;
      }
      if (other.BgKind != 0) {
        BgKind = other.BgKind;
      }
      if (other.BgIndex != 0) {
        BgIndex = other.BgIndex;
      }
      if (other.BgRgb != 0) {
        BgRgb = other.BgRgb;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Rune = input.ReadInt32();
            break;
          }
          case 16: {
            Fg = input.ReadUInt32();
            break;
          }
          case 24: {
            Bg = input.ReadUInt32();
            break;
          }
          case 32: {
            Attrs = input.ReadUInt32();
            break;
          }
          case 40: {
            Width = input.ReadUInt32();
            break;
          }
          case 48: {
            FgKind = input.ReadUInt32();
            break;
          }
          case 56: {
            FgIndex = input.ReadUInt32();
            break;
          }
          case 64: {
            FgRgb = input.ReadUInt32();
            break;
          }
          case 72: {
            BgKind = input.ReadUInt32();
            break;
          }
          case 80: {
            BgIndex = input.ReadUInt32();
            break;
          }
          case 88: {
            BgRgb = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Rune = input.ReadInt32();
            break;
          }
          case 16: {
            Fg = input.ReadUInt32();
            break;
          }
          case 24: {
            Bg = input.ReadUInt32();
            break;
          }
          case 32: {
            Attrs = input.ReadUInt32();
            break;
          }
          case 40: {
            Width = input.ReadUInt32();
            break;
          }
          case 48: {
            FgKind = input.ReadUInt32();
            break;
          }
          case 56: {
            FgIndex = input.ReadUInt32();
            break;
          }
          case 64: {
            FgRgb = input.ReadUInt32();
            break;
          }
          case 72: {
            BgKind = input.ReadUInt32();
            break;
          }
          case 80: {
            BgIndex = input.ReadUInt32();
            break;
          }
          case 88: {
            BgRgb = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class PRow : pb::IMessage<PRow>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PRow> _parser = new pb::MessageParser<PRow>(() => new PRow());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PRow> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Agwinterm.Core.Persist.PersistReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PRow() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PRow(PRow other) : this() {
      cells_ = other.cells_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PRow Clone() {
      return new PRow(this);
    }

    /// <summary>Field number for the "cells" field.</summary>
    public const int CellsFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Agwinterm.Core.Persist.PCell> _repeated_cells_codec
        = pb::FieldCodec.ForMessage(10, global::Agwinterm.Core.Persist.PCell.Parser);
    private readonly pbc::RepeatedField<global::Agwinterm.Core.Persist.PCell> cells_ = new pbc::RepeatedField<global::Agwinterm.Core.Persist.PCell>();
    /// <summary>
    /// trimmed to the row's content (reads pad with empty)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Agwinterm.Core.Persist.PCell> Cells {
      get { return cells_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PRow);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PRow other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!cells_.Equals(other.cells_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= cells_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      cells_.WriteTo(output, _repeated_cells_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      cells_.WriteTo(ref output, _repeated_cells_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += cells_.CalculateSize(_repeated_cells_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PRow other) {
      if (other == null) {
        return;
      }
      cells_.Add(other.cells_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            cells_.AddEntriesFrom(input, _repeated_cells_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            cells_.AddEntriesFrom(ref input, _repeated_cells_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class PBuffer : pb::IMessage<PBuffer>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PBuffer> _parser = new pb::MessageParser<PBuffer>(() => new PBuffer());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PBuffer> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Agwinterm.Core.Persist.PersistReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PBuffer() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PBuffer(PBuffer other) : this() {
      version_ = other.version_;
      cols_ = other.cols_;
      rows_ = other.rows_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PBuffer Clone() {
      return new PBuffer(this);
    }

    /// <summary>Field number for the "version" field.</summary>
    public const int VersionFieldNumber = 1;
    private uint version_;
    /// <summary>
    /// 1 = this layout
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Version {
      get { return version_; }
      set {
        version_ = value;
      }
    }

    /// <summary>Field number for the "cols" field.</summary>
    public const int ColsFieldNumber = 2;
    private uint cols_;
    /// <summary>
    /// width the rows were captured at
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Cols {
      get { return cols_; }
      set {
        cols_ = value;
      }
    }

    /// <summary>Field number for the "rows" field.</summary>
    public const int RowsFieldNumber = 3;
    private static readonly pb::FieldCodec<global::Agwinterm.Core.Persist.PRow> _repeated_rows_codec
        = pb::FieldCodec.ForMessage(26, global::Agwinterm.Core.Persist.PRow.Parser);
    private readonly pbc::RepeatedField<global::Agwinterm.Core.Persist.PRow> rows_ = new pbc::RepeatedField<global::Agwinterm.Core.Persist.PRow>();
    /// <summary>
    /// scrollback + captured live rows, oldest first
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Agwinterm.Core.Persist.PRow> Rows {
      get { return rows_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PBuffer);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PBuffer other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Version != other.Version) return false;
      if (Cols != other.Cols) return false;
      if(!rows_.Equals(other.rows_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Version != 0) hash ^= Version.GetHashCode();
      if (Cols != 0) hash ^= Cols.GetHashCode();
      hash ^= rows_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Version != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Version);
      }
      if (Cols != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Cols);
      }
      rows_.WriteTo(output, _repeated_rows_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Version != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Version);
      }
      if (Cols != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Cols);
      }
      rows_.WriteTo(ref output, _repeated_rows_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Version != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Version);
      }
      if (Cols != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Cols);
      }
      size += rows_.CalculateSize(_repeated_rows_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PBuffer other) {
      if (other == null) {
        return;
      }
      if (other.Version != 0) {
        Version = other.Version;
      }
      if (other.Cols != 0) {
        Cols = other.Cols;
      }
      rows_.Add(other.rows_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Version = input.ReadUInt32();
            break;
          }
          case 16: {
            Cols = input.ReadUInt32();
            break;
          }
          case 26: {
            rows_.AddEntriesFrom(input, _repeated_rows_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Version = input.ReadUInt32();
            break;
          }
          case 16: {
            Cols = input.ReadUInt32();
            break;
          }
          case 26: {
            rows_.AddEntriesFrom(ref input, _repeated_rows_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
