/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9 */

#include "ptyhost.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(agwinterm_ptyhost_Request, agwinterm_ptyhost_Request, 4)


PB_BIND(agwinterm_ptyhost_Hello, agwinterm_ptyhost_Hello, AUTO)


PB_BIND(agwinterm_ptyhost_Create, agwinterm_ptyhost_Create, 4)


PB_BIND(agwinterm_ptyhost_Create_EnvEntry, agwinterm_ptyhost_Create_EnvEntry, 2)


PB_BIND(agwinterm_ptyhost_Attach, agwinterm_ptyhost_Attach, AUTO)


PB_BIND(agwinterm_ptyhost_SessionRef, agwinterm_ptyhost_SessionRef, AUTO)


PB_BIND(agwinterm_ptyhost_Resize, agwinterm_ptyhost_Resize, AUTO)


PB_BIND(agwinterm_ptyhost_List, agwinterm_ptyhost_List, AUTO)


PB_BIND(agwinterm_ptyhost_Shutdown, agwinterm_ptyhost_Shutdown, AUTO)


PB_BIND(agwinterm_ptyhost_Reply, agwinterm_ptyhost_Reply, 4)


PB_BIND(agwinterm_ptyhost_HelloReply, agwinterm_ptyhost_HelloReply, AUTO)


PB_BIND(agwinterm_ptyhost_CreateReply, agwinterm_ptyhost_CreateReply, AUTO)


PB_BIND(agwinterm_ptyhost_AttachReply, agwinterm_ptyhost_AttachReply, 2)


PB_BIND(agwinterm_ptyhost_SessionInfo, agwinterm_ptyhost_SessionInfo, 2)


PB_BIND(agwinterm_ptyhost_ListReply, agwinterm_ptyhost_ListReply, 4)



