// This file is @generated by prost-build.
/// One cell. Colours are 0x00RRGGBB; specs mirror ColorSpec (kind 0 default /
/// 1 indexed / 2 rgb). Fields are packed to keep the blob small: most cells are
/// a rune with default everything, so proto3's "omit defaults" does the work.
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct PCell {
    #[prost(int32, tag = "1")]
    pub rune: i32,
    #[prost(uint32, tag = "2")]
    pub fg: u32,
    #[prost(uint32, tag = "3")]
    pub bg: u32,
    #[prost(uint32, tag = "4")]
    pub attrs: u32,
    /// 1 normal, 2 wide lead, 0 trailing spacer
    #[prost(uint32, tag = "5")]
    pub width: u32,
    #[prost(uint32, tag = "6")]
    pub fg_kind: u32,
    #[prost(uint32, tag = "7")]
    pub fg_index: u32,
    #[prost(uint32, tag = "8")]
    pub fg_rgb: u32,
    #[prost(uint32, tag = "9")]
    pub bg_kind: u32,
    #[prost(uint32, tag = "10")]
    pub bg_index: u32,
    #[prost(uint32, tag = "11")]
    pub bg_rgb: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PRow {
    /// trimmed to the row's content (reads pad with empty)
    #[prost(message, repeated, tag = "1")]
    pub cells: ::prost::alloc::vec::Vec<PCell>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PBuffer {
    /// 1 = this layout
    #[prost(uint32, tag = "1")]
    pub version: u32,
    /// width the rows were captured at
    #[prost(uint32, tag = "2")]
    pub cols: u32,
    /// scrollback + captured live rows, oldest first
    #[prost(message, repeated, tag = "3")]
    pub rows: ::prost::alloc::vec::Vec<PRow>,
}
