// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Request {
    #[prost(oneof = "request::Cmd", tags = "1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11")]
    pub cmd: ::core::option::Option<request::Cmd>,
}
/// Nested message and enum types in `Request`.
pub mod request {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Cmd {
        #[prost(message, tag = "1")]
        Hello(super::Hello),
        #[prost(message, tag = "2")]
        Create(super::Create),
        #[prost(message, tag = "3")]
        Attach(super::Attach),
        #[prost(message, tag = "4")]
        Detach(super::SessionRef),
        #[prost(message, tag = "5")]
        Resize(super::Resize),
        #[prost(message, tag = "6")]
        Kill(super::SessionRef),
        #[prost(message, tag = "7")]
        List(super::List),
        #[prost(message, tag = "8")]
        Shutdown(super::Shutdown),
        #[prost(message, tag = "9")]
        PrepareCreate(super::PrepareCreate),
        #[prost(message, tag = "10")]
        QueryCreate(super::CreationRef),
        #[prost(message, tag = "11")]
        CancelCreate(super::CreationRef),
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Hello {
    /// must equal the host's version (2 = protobuf wire)
    #[prost(uint32, tag = "1")]
    pub protocol: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Create {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub cols: u32,
    #[prost(uint32, tag = "3")]
    pub rows: u32,
    #[prost(string, tag = "4")]
    pub app: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "5")]
    pub args: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// empty = inherit
    #[prost(string, tag = "6")]
    pub cwd: ::prost::alloc::string::String,
    #[prost(bool, tag = "7")]
    pub verbatim: bool,
    #[prost(bool, tag = "8")]
    pub de_elevate: bool,
    /// proto3 default false = freshEnv ON (matches v1 semantics)
    #[prost(bool, tag = "9")]
    pub fresh_env_off: bool,
    #[prost(map = "string, string", tag = "10")]
    pub env: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
    /// creation_revision >= 1: host-issued, single-use spawn authority
    #[prost(string, tag = "11")]
    pub creation_ticket: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Attach {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub repaint: bool,
    /// optional expected incarnation; mismatch refuses
    #[prost(string, tag = "3")]
    pub creation_ticket: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SessionRef {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// optional expected incarnation; mismatch refuses
    #[prost(string, tag = "2")]
    pub creation_ticket: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Resize {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub cols: u32,
    #[prost(uint32, tag = "3")]
    pub rows: u32,
    /// optional expected incarnation; mismatch refuses
    #[prost(string, tag = "4")]
    pub creation_ticket: ::prost::alloc::string::String,
}
/// Preparation never starts a child. A lost prepare reply may be abandoned safely. A client must
/// never allocate a replacement ticket or replay a legacy create after an ambiguous create reply.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PrepareCreate {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreationRef {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub ticket: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreationReply {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub ticket: ::prost::alloc::string::String,
    #[prost(enumeration = "CreationPhase", tag = "3")]
    pub phase: i32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct List {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Shutdown {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Reply {
    #[prost(bool, tag = "1")]
    pub ok: bool,
    /// set when ok = false
    #[prost(string, tag = "2")]
    pub error: ::prost::alloc::string::String,
    #[prost(oneof = "reply::Body", tags = "3, 4, 5, 6, 7")]
    pub body: ::core::option::Option<reply::Body>,
}
/// Nested message and enum types in `Reply`.
pub mod reply {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Body {
        #[prost(message, tag = "3")]
        Hello(super::HelloReply),
        #[prost(message, tag = "4")]
        Create(super::CreateReply),
        #[prost(message, tag = "5")]
        Attach(super::AttachReply),
        #[prost(message, tag = "6")]
        List(super::ListReply),
        #[prost(message, tag = "7")]
        Creation(super::CreationReply),
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct HelloReply {
    #[prost(uint32, tag = "1")]
    pub protocol: u32,
    #[prost(uint32, tag = "2")]
    pub pid: u32,
    /// 0 = legacy limitations; 1 = prepare/query/cancel + incarnation checks
    #[prost(uint32, tag = "3")]
    pub creation_revision: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateReply {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub creation_ticket: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AttachReply {
    /// data-pipe name to connect
    #[prost(string, tag = "1")]
    pub pipe: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub cols: u32,
    #[prost(uint32, tag = "3")]
    pub rows: u32,
    /// 0 = unknown
    #[prost(uint32, tag = "4")]
    pub child_pid: u32,
    #[prost(bool, tag = "5")]
    pub has_exited: bool,
    #[prost(int32, tag = "6")]
    pub exit_code: i32,
    /// synthesized VT reproducing mode state (DumpModes)
    #[prost(string, tag = "7")]
    pub modes: ::prost::alloc::string::String,
    /// plain-text history rows, oldest first (back-compat / lite)
    #[prost(string, repeated, tag = "8")]
    pub scrollback: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Full-fidelity attributed scrollback: a serialized agwinterm.persist.PBuffer of the HISTORY
    /// rows (colours + styles). When present the client seeds from this instead of the plain text,
    /// so a reattached view is not dim-until-repaint. Empty when the host can't produce it (a Rust
    /// host without persist support yet); the client falls back to `scrollback`.
    #[prost(bytes = "vec", tag = "9")]
    pub scrollback_blob: ::prost::alloc::vec::Vec<u8>,
    #[prost(string, tag = "10")]
    pub creation_ticket: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SessionInfo {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub cols: u32,
    #[prost(uint32, tag = "3")]
    pub rows: u32,
    #[prost(uint32, tag = "4")]
    pub child_pid: u32,
    #[prost(bool, tag = "5")]
    pub has_exited: bool,
    #[prost(int32, tag = "6")]
    pub exit_code: i32,
    #[prost(string, tag = "7")]
    pub title: ::prost::alloc::string::String,
    #[prost(bool, tag = "8")]
    pub attached: bool,
    #[prost(string, tag = "9")]
    pub creation_ticket: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListReply {
    #[prost(message, repeated, tag = "1")]
    pub sessions: ::prost::alloc::vec::Vec<SessionInfo>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CreationPhase {
    /// cannot start or address a child under this ticket
    CreationUnknown = 0,
    CreationPrepared = 1,
    CreationCreating = 2,
    CreationLive = 3,
    /// cleanup requested, NOT yet proven complete
    CreationCancelling = 4,
}
impl CreationPhase {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::CreationUnknown => "CREATION_UNKNOWN",
            Self::CreationPrepared => "CREATION_PREPARED",
            Self::CreationCreating => "CREATION_CREATING",
            Self::CreationLive => "CREATION_LIVE",
            Self::CreationCancelling => "CREATION_CANCELLING",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CREATION_UNKNOWN" => Some(Self::CreationUnknown),
            "CREATION_PREPARED" => Some(Self::CreationPrepared),
            "CREATION_CREATING" => Some(Self::CreationCreating),
            "CREATION_LIVE" => Some(Self::CreationLive),
            "CREATION_CANCELLING" => Some(Self::CreationCancelling),
            _ => None,
        }
    }
}
