// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Request {
    #[prost(oneof = "request::Cmd", tags = "1, 2, 3, 4, 5, 6, 7, 8")]
    pub cmd: ::core::option::Option<request::Cmd>,
}
/// Nested message and enum types in `Request`.
pub mod request {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Cmd {
        #[prost(message, tag = "1")]
        Hello(super::Hello),
        #[prost(message, tag = "2")]
        Create(super::Create),
        #[prost(message, tag = "3")]
        Attach(super::Attach),
        #[prost(message, tag = "4")]
        Detach(super::SessionRef),
        #[prost(message, tag = "5")]
        Resize(super::Resize),
        #[prost(message, tag = "6")]
        Kill(super::SessionRef),
        #[prost(message, tag = "7")]
        List(super::List),
        #[prost(message, tag = "8")]
        Shutdown(super::Shutdown),
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Hello {
    /// must equal the host's version (2 = protobuf wire)
    #[prost(uint32, tag = "1")]
    pub protocol: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Create {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub cols: u32,
    #[prost(uint32, tag = "3")]
    pub rows: u32,
    #[prost(string, tag = "4")]
    pub app: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "5")]
    pub args: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// empty = inherit
    #[prost(string, tag = "6")]
    pub cwd: ::prost::alloc::string::String,
    #[prost(bool, tag = "7")]
    pub verbatim: bool,
    #[prost(bool, tag = "8")]
    pub de_elevate: bool,
    /// proto3 default false = freshEnv ON (matches v1 semantics)
    #[prost(bool, tag = "9")]
    pub fresh_env_off: bool,
    #[prost(map = "string, string", tag = "10")]
    pub env: ::std::collections::HashMap<
        ::prost::alloc::string::String,
        ::prost::alloc::string::String,
    >,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Attach {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(bool, tag = "2")]
    pub repaint: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SessionRef {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Resize {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub cols: u32,
    #[prost(uint32, tag = "3")]
    pub rows: u32,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct List {}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct Shutdown {}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Reply {
    #[prost(bool, tag = "1")]
    pub ok: bool,
    /// set when ok = false
    #[prost(string, tag = "2")]
    pub error: ::prost::alloc::string::String,
    #[prost(oneof = "reply::Body", tags = "3, 4, 5, 6")]
    pub body: ::core::option::Option<reply::Body>,
}
/// Nested message and enum types in `Reply`.
pub mod reply {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Body {
        #[prost(message, tag = "3")]
        Hello(super::HelloReply),
        #[prost(message, tag = "4")]
        Create(super::CreateReply),
        #[prost(message, tag = "5")]
        Attach(super::AttachReply),
        #[prost(message, tag = "6")]
        List(super::ListReply),
    }
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct HelloReply {
    #[prost(uint32, tag = "1")]
    pub protocol: u32,
    #[prost(uint32, tag = "2")]
    pub pid: u32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateReply {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AttachReply {
    /// data-pipe name to connect
    #[prost(string, tag = "1")]
    pub pipe: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub cols: u32,
    #[prost(uint32, tag = "3")]
    pub rows: u32,
    /// 0 = unknown
    #[prost(uint32, tag = "4")]
    pub child_pid: u32,
    #[prost(bool, tag = "5")]
    pub has_exited: bool,
    #[prost(int32, tag = "6")]
    pub exit_code: i32,
    /// synthesized VT reproducing mode state (DumpModes)
    #[prost(string, tag = "7")]
    pub modes: ::prost::alloc::string::String,
    /// plain-text history rows, oldest first
    #[prost(string, repeated, tag = "8")]
    pub scrollback: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SessionInfo {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(uint32, tag = "2")]
    pub cols: u32,
    #[prost(uint32, tag = "3")]
    pub rows: u32,
    #[prost(uint32, tag = "4")]
    pub child_pid: u32,
    #[prost(bool, tag = "5")]
    pub has_exited: bool,
    #[prost(int32, tag = "6")]
    pub exit_code: i32,
    #[prost(string, tag = "7")]
    pub title: ::prost::alloc::string::String,
    #[prost(bool, tag = "8")]
    pub attached: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListReply {
    #[prost(message, repeated, tag = "1")]
    pub sessions: ::prost::alloc::vec::Vec<SessionInfo>,
}
